/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PurseReturnRouteImport } from './routes/purse.return'
import { Route as StoryIndexRouteImport } from './routes/story.index'
import { Route as StoryNodeIdRouteImport } from './routes/story.$nodeId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PurseReturnRoute = PurseReturnRouteImport.update({
  id: '/purse/return',
  path: '/purse/return',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIndexRoute = StoryIndexRouteImport.update({
  id: '/story/',
  path: '/story/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryNodeIdRoute = StoryNodeIdRouteImport.update({
  id: '/story/$nodeId',
  path: '/story/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/purse/return': typeof PurseReturnRoute
  '/story/$nodeId': typeof StoryNodeIdRoute
  '/story/': typeof StoryIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/purse/return': typeof PurseReturnRoute
  '/story/$nodeId': typeof StoryNodeIdRoute
  '/story': typeof StoryIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/purse/return': typeof PurseReturnRoute
  '/story/$nodeId': typeof StoryNodeIdRoute
  '/story/': typeof StoryIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/sitemap.xml'
    | '/purse/return'
    | '/story/$nodeId'
    | '/story/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/sitemap.xml'
    | '/purse/return'
    | '/story/$nodeId'
    | '/story'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/profile'
    | '/sitemap.xml'
    | '/purse/return'
    | '/story/$nodeId'
    | '/story/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PurseReturnRoute: typeof PurseReturnRoute
  StoryNodeIdRoute: typeof StoryNodeIdRoute
  StoryIndexRoute: typeof StoryIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purse/return': {
      id: '/purse/return'
      path: '/purse/return'
      fullPath: '/purse/return'
      preLoaderRoute: typeof PurseReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/': {
      id: '/story/'
      path: '/story'
      fullPath: '/story/'
      preLoaderRoute: typeof StoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$nodeId': {
      id: '/story/$nodeId'
      path: '/story/$nodeId'
      fullPath: '/story/$nodeId'
      preLoaderRoute: typeof StoryNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PurseReturnRoute: PurseReturnRoute,
  StoryNodeIdRoute: StoryNodeIdRoute,
  StoryIndexRoute: StoryIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
